### PR TITLE
Fix audio on Safari (fix #25)

### LINKED ISSUE #25: Safari: audio doesn't play
Seems to be an InvalidStateError when running audio scheduler code.

Screen Shot 2019-05-21 at 12 24 29 PM

### PR DESCRIPTION
**Pull request by tmickel**
1. Convert all assets to .mp3, since ogg is not supported by Safari.
2. Use a callback-oriented decodeAudioData, since Safari doesn't support the Promise version. Also stopped waiting for that promise/callback to resolve (since it wasn't blocking anything).

### CODE REVIEW

File: src/Audio/PlayHead.ts [hunk 1]
```diff
@@ -233,6 +236,5 @@ export default class PlayHead {
     }
     this.gain.gain.cancelScheduledValues(0);
     this.gain.gain.linearRampToValueAtTime(0.000001, stopTime);
-    this.source.stop(stopTime);
```
Comment (tmickel) [inline src/Audio/PlayHead.ts]: This line was causing problems with Safari during dragging a note, and is also unnecessary.

File: src/Palette/CategoryMenu.css [hunk 2]
```diff
@@ -12,7 +12,7 @@
   text-align: center;
   display: block;
   margin: auto;
-  background: rgb(0, 0, 0, 0);
+  background: transparent;
```
Comment (tmickel) [inline src/Palette/CategoryMenu.css]: Fixes the category menu appearance in Safari on my local dev.
